version: '3'
services:
  alc_api:
    build: .
    image: mymealplan-api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: bash -c "cd /api && DEBUG=True python3 manage.py runserver_plus 0.0.0.0:8000"
  alc_ui:
    image: mymealplan-client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/client
    command: bash -c "cd /client && npm start"
