# Generated by Django 2.2.4 on 2019-09-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_recipe_meal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='budget_type',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
