# Generated by Django 2.2.4 on 2019-09-03 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190903_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='api.RestrictionTag'),
        ),
    ]
